; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature --include-generated-funcs
; RUN: opt -S --passes=always-specialize < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: noinline nounwind
define dso_local i32 @leaf(i32 alwaysspecialize %x, i32 alwaysspecialize %y) #0 {
entry:
  %add = add nsw i32 %x, %y
  ret i32 %add
}

; Function Attrs: noinline nounwind
define dso_local i32 @in_order(i32 alwaysspecialize %x) #0 {
entry:
  %call = call i32 @leaf(i32 42, i32 %x) #1
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @swapped(i32 alwaysspecialize %x) #0 {
entry:
  %call = call i32 @leaf(i32 %x, i32 81) #1
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @root() #0 {
entry:
  %call = call i32 @in_order(i32 81) #1
  %call1 = call i32 @swapped(i32 42) #1
  %mul = mul nsw i32 %call, %call1
  ret i32 %mul
}

attributes #0 = { noinline nounwind "frame-pointer"="all" "min-legal-vector-width"="0" "no-builtins" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nobuiltin "no-builtins" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 20.0.0git (git@github.com:llvm/llvm-project.git 8de87910aa5e588898756807e8075169fb6e166d)"}
; CHECK-LABEL: define {{[^@]+}}@leaf
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]], i32 alwaysspecialize [[Y:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define {{[^@]+}}@in_order
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @leaf.spec0(i32 42, i32 [[X]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@swapped
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @leaf.spec1(i32 [[X]], i32 81) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@root
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @in_order.spec0(i32 81) #[[ATTR1]]
; CHECK-NEXT:    [[CALL1:%.*]] = call i32 @swapped.spec0(i32 42) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[CALL]], [[CALL1]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@leaf.spec0
; CHECK-SAME: (i32 [[X:%.*]], i32 alwaysspecialize [[Y:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 42, [[Y]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define {{[^@]+}}@leaf.spec1
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]], i32 [[Y:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 81
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define {{[^@]+}}@in_order.spec0
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @leaf.spec0.spec1(i32 42, i32 81) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@swapped.spec0
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @leaf.spec1.spec0(i32 42, i32 81) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@leaf.spec0.spec1
; CHECK-SAME: (i32 [[X:%.*]], i32 [[Y:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 42, 81
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define {{[^@]+}}@leaf.spec1.spec0
; CHECK-SAME: (i32 [[X:%.*]], i32 [[Y:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 42, 81
; CHECK-NEXT:    ret i32 [[ADD]]
;
