; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature --include-generated-funcs
; RUN: opt -S --passes=always-specialize < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@ptrfirst.x = internal global i32 42, align 4
@ptrboth.x = internal global i32 42, align 4
@ptrboth.y = internal constant i32 81, align 4
@ptrallsame.x = internal global i32 42, align 4

; Function Attrs: noinline nounwind
define dso_local i32 @callee(i32 alwaysspecialize %x, i32 %y, i32 alwaysspecialize %z) #0 {
entry:
  %add = add nsw i32 %x, %z
  %mul = mul nsw i32 %add, %z
  ret i32 %mul
}

; Function Attrs: noinline nounwind
define dso_local i32 @first(i32 %a, i32 %b) #0 {
entry:
  %call = call i32 @callee(i32 42, i32 %a, i32 %b) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @second(i32 %a, i32 %b) #0 {
entry:
  %call = call i32 @callee(i32 %a, i32 42, i32 %b) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @third(i32 %a, i32 %b) #0 {
entry:
  %call = call i32 @callee(i32 %a, i32 %b, i32 42) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @both(i32 %a) #0 {
entry:
  %call = call i32 @callee(i32 21, i32 %a, i32 42) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @ptrcallee(ptr alwaysspecialize %x, ptr %y, ptr alwaysspecialize %z) #0 {
entry:
  %0 = load i32, ptr %x, align 4
  %1 = load i32, ptr %z, align 4
  %add = add nsw i32 %0, %1
  %2 = load i32, ptr %z, align 4
  %mul = mul nsw i32 %add, %2
  ret i32 %mul
}

; Function Attrs: noinline nounwind
define dso_local i32 @ptrfirst(ptr %a, ptr %b) #0 {
entry:
  %call = call i32 @ptrcallee(ptr @ptrfirst.x, ptr %a, ptr %b) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @ptrboth(ptr %a) #0 {
entry:
  %call = call i32 @ptrcallee(ptr @ptrboth.x, ptr %a, ptr @ptrboth.y) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @ptrallsame() #0 {
entry:
  %call = call i32 @ptrcallee(ptr @ptrallsame.x, ptr @ptrallsame.x, ptr @ptrallsame.x) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @virtualcall(ptr alwaysspecialize %func, i32 %x) #0 {
entry:
  %call = call i32 %func(i32 %x) #2
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @devirtualisecaller(i32 %x) #0 {
entry:
  %call = call i32 @virtualcall(ptr @virtualcallee, i32 %x) #2
  ret i32 %call
}

declare i32 @virtualcallee(i32 noundef) #1

attributes #0 = { noinline nounwind "frame-pointer"="all" "min-legal-vector-width"="0" "no-builtins" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="all" "no-builtins" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { nobuiltin "no-builtins" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 20.0.0git (git@github.com:llvm/llvm-project.git 8de87910aa5e588898756807e8075169fb6e166d)"}
; CHECK-LABEL: define {{[^@]+}}@callee
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]], i32 [[Y:%.*]], i32 alwaysspecialize [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], [[Z]]
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], [[Z]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@first
; CHECK-SAME: (i32 [[A:%.*]], i32 [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @callee.spec0.3(i32 42, i32 [[A]], i32 [[B]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@second
; CHECK-SAME: (i32 [[A:%.*]], i32 [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @callee(i32 [[A]], i32 42, i32 [[B]]) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@third
; CHECK-SAME: (i32 [[A:%.*]], i32 [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @callee.spec2(i32 [[A]], i32 [[B]], i32 42) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@both
; CHECK-SAME: (i32 [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @callee.spec0.spec2(i32 21, i32 [[A]], i32 42) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrcallee
; CHECK-SAME: (ptr alwaysspecialize [[X:%.*]], ptr [[Y:%.*]], ptr alwaysspecialize [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[Z]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[Z]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], [[TMP2]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrfirst
; CHECK-SAME: (ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @ptrcallee.spec0.9(ptr @ptrfirst.x, ptr [[A]], ptr [[B]]) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrboth
; CHECK-SAME: (ptr [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @ptrcallee.spec0.7.spec2(ptr @ptrboth.x, ptr [[A]], ptr @ptrboth.y) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrallsame
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @ptrcallee.spec0.spec2(ptr @ptrallsame.x, ptr @ptrallsame.x, ptr @ptrallsame.x) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@virtualcall
; CHECK-SAME: (ptr alwaysspecialize [[FUNC:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 [[FUNC]](i32 [[X]]) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@devirtualisecaller
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @virtualcall.spec0(ptr @virtualcallee, i32 [[X]]) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@callee.spec0.3
; CHECK-SAME: (i32 [[X:%.*]], i32 [[Y:%.*]], i32 alwaysspecialize [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 42, [[Z]]
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], [[Z]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@callee.spec2
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[X]], 42
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], 42
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrcallee.spec0.9
; CHECK-SAME: (ptr [[X:%.*]], ptr [[Y:%.*]], ptr alwaysspecialize [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @ptrfirst.x, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[Z]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[Z]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], [[TMP2]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@virtualcall.spec0
; CHECK-SAME: (ptr [[FUNC:%.*]], i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @virtualcallee(i32 [[X]]) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@callee.spec0.spec2
; CHECK-SAME: (i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 21, 42
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], 42
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrcallee.spec0.spec2
; CHECK-SAME: (ptr [[X:%.*]], ptr [[Y:%.*]], ptr [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @ptrallsame.x, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @ptrallsame.x, align 4
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr @ptrallsame.x, align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], [[TMP2]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@ptrcallee.spec0.7.spec2
; CHECK-SAME: (ptr [[X:%.*]], ptr [[Y:%.*]], ptr [[Z:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @ptrboth.x, align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @ptrboth.y, align 4
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr @ptrboth.y, align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[ADD]], [[TMP2]]
; CHECK-NEXT:    ret i32 [[MUL]]
;
