; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature --include-generated-funcs
; RUN: opt -S --passes=always-specialize < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: noinline nounwind
define dso_local i32 @loop(i32 alwaysspecialize %x) #0 {
entry:
  %call = call i32 @loop(i32 5) #1
  %call1 = call i32 @loop(i32 %x) #1
  %add = add i32 %call, %call1
  ret i32 %add
}

; Function Attrs: noinline nounwind
define dso_local i32 @loop_driver() #0 {
entry:
  %call = call i32 @loop(i32 5) #1
  ret i32 %call
}

; Function Attrs: noinline nounwind
define dso_local i32 @factorial(i32 alwaysspecialize %x) #0 {
entry:
  %cmp = icmp ult i32 %x, 2
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  br label %return

if.end:                                           ; preds = %entry
  %sub = sub i32 %x, 1
  %call = call i32 @factorial(i32 %sub) #1
  %mul = mul i32 %x, %call
  br label %return

return:                                           ; preds = %if.end, %if.then
  %retval.0 = phi i32 [ 1, %if.then ], [ %mul, %if.end ]
  ret i32 %retval.0
}

; Function Attrs: noinline nounwind
define dso_local i32 @factorial_driver() #0 {
entry:
  %call = call i32 @factorial(i32 0) #1
  %call1 = call i32 @factorial(i32 1) #1
  %add = add i32 %call, %call1
  %call2 = call i32 @factorial(i32 2) #1
  %add3 = add i32 %add, %call2
  %call4 = call i32 @factorial(i32 3) #1
  %add5 = add i32 %add3, %call4
  %call6 = call i32 @factorial(i32 4) #1
  %add7 = add i32 %add5, %call6
  ret i32 %add7
}

; Function Attrs: noinline nounwind
define dso_local zeroext i1 @odd(i32 alwaysspecialize %x) #0 {
entry:
  %cmp = icmp eq i32 %x, 0
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  br label %cond.end

cond.false:                                       ; preds = %entry
  %sub = sub i32 %x, 1
  %call = call zeroext i1 @even(i32 %sub) #1
  %conv = zext i1 %call to i32
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond = phi i32 [ 0, %cond.true ], [ %conv, %cond.false ]
  %tobool = icmp ne i32 %cond, 0
  ret i1 %tobool
}

; Function Attrs: noinline nounwind
define dso_local zeroext i1 @even(i32 alwaysspecialize %x) #0 {
entry:
  %cmp = icmp eq i32 %x, 0
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:                                        ; preds = %entry
  br label %cond.end

cond.false:                                       ; preds = %entry
  %sub = sub i32 %x, 1
  %call = call zeroext i1 @odd(i32 %sub) #1
  %conv = zext i1 %call to i32
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %cond = phi i32 [ 1, %cond.true ], [ %conv, %cond.false ]
  %tobool = icmp ne i32 %cond, 0
  ret i1 %tobool
}

; Function Attrs: noinline nounwind
define dso_local zeroext i1 @evenodd_driver() #0 {
entry:
  %call = call zeroext i1 @even(i32 0) #1
  br i1 %call, label %land.lhs.true, label %land.end

land.lhs.true:                                    ; preds = %entry
  %call1 = call zeroext i1 @even(i32 1) #1
  br i1 %call1, label %land.end, label %land.lhs.true2

land.lhs.true2:                                   ; preds = %land.lhs.true
  %call3 = call zeroext i1 @even(i32 2) #1
  br i1 %call3, label %land.lhs.true4, label %land.end

land.lhs.true4:                                   ; preds = %land.lhs.true2
  %call5 = call zeroext i1 @even(i32 3) #1
  br i1 %call5, label %land.end, label %land.lhs.true6

land.lhs.true6:                                   ; preds = %land.lhs.true4
  %call7 = call zeroext i1 @odd(i32 0) #1
  br i1 %call7, label %land.end, label %land.lhs.true8

land.lhs.true8:                                   ; preds = %land.lhs.true6
  %call9 = call zeroext i1 @odd(i32 1) #1
  br i1 %call9, label %land.lhs.true10, label %land.end

land.lhs.true10:                                  ; preds = %land.lhs.true8
  %call11 = call zeroext i1 @odd(i32 2) #1
  br i1 %call11, label %land.end, label %land.rhs

land.rhs:                                         ; preds = %land.lhs.true10
  %call12 = call zeroext i1 @odd(i32 3) #1
  br label %land.end

land.end:                                         ; preds = %land.rhs, %land.lhs.true10, %land.lhs.true8, %land.lhs.true6, %land.lhs.true4, %land.lhs.true2, %land.lhs.true, %entry
  %0 = phi i1 [ false, %land.lhs.true10 ], [ false, %land.lhs.true8 ], [ false, %land.lhs.true6 ], [ false, %land.lhs.true4 ], [ false, %land.lhs.true2 ], [ false, %land.lhs.true ], [ false, %entry ], [ %call12, %land.rhs ]
  ret i1 %0
}

attributes #0 = { noinline nounwind "frame-pointer"="all" "min-legal-vector-width"="0" "no-builtins" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nobuiltin "no-builtins" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{!"clang version 20.0.0git (git@github.com:llvm/llvm-project.git 8de87910aa5e588898756807e8075169fb6e166d)"}
; CHECK-LABEL: define {{[^@]+}}@loop
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @loop.spec0(i32 5) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[CALL1:%.*]] = call i32 @loop(i32 [[X]]) #[[ATTR1]]
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[CALL]], [[CALL1]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define {{[^@]+}}@loop_driver
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @loop.spec0(i32 5) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[CALL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X]], 2
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 [[X]], 1
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[X]], [[CALL]]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ [[MUL]], [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial_driver
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial.spec0.10(i32 0) #[[ATTR1]]
; CHECK-NEXT:    [[CALL1:%.*]] = call i32 @factorial.spec0.8(i32 1) #[[ATTR1]]
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[CALL]], [[CALL1]]
; CHECK-NEXT:    [[CALL2:%.*]] = call i32 @factorial.spec0.6(i32 2) #[[ATTR1]]
; CHECK-NEXT:    [[ADD3:%.*]] = add i32 [[ADD]], [[CALL2]]
; CHECK-NEXT:    [[CALL4:%.*]] = call i32 @factorial.spec0.4(i32 3) #[[ATTR1]]
; CHECK-NEXT:    [[ADD5:%.*]] = add i32 [[ADD3]], [[CALL4]]
; CHECK-NEXT:    [[CALL6:%.*]] = call i32 @factorial.spec0(i32 4) #[[ATTR1]]
; CHECK-NEXT:    [[ADD7:%.*]] = add i32 [[ADD5]], [[CALL6]]
; CHECK-NEXT:    ret i32 [[ADD7]]
;
;
; CHECK-LABEL: define {{[^@]+}}@odd
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 [[X]], 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @even(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 0, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@even
; CHECK-SAME: (i32 alwaysspecialize [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 [[X]], 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @odd(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 1, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@evenodd_driver
; CHECK-SAME: () #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @even.spec0.24(i32 0) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL]], label [[LAND_LHS_TRUE:%.*]], label [[LAND_END:%.*]]
; CHECK:       land.lhs.true:
; CHECK-NEXT:    [[CALL1:%.*]] = call zeroext i1 @even.spec0.22(i32 1) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL1]], label [[LAND_END]], label [[LAND_LHS_TRUE2:%.*]]
; CHECK:       land.lhs.true2:
; CHECK-NEXT:    [[CALL3:%.*]] = call zeroext i1 @even.spec0.20(i32 2) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL3]], label [[LAND_LHS_TRUE4:%.*]], label [[LAND_END]]
; CHECK:       land.lhs.true4:
; CHECK-NEXT:    [[CALL5:%.*]] = call zeroext i1 @even.spec0(i32 3) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL5]], label [[LAND_END]], label [[LAND_LHS_TRUE6:%.*]]
; CHECK:       land.lhs.true6:
; CHECK-NEXT:    [[CALL7:%.*]] = call zeroext i1 @odd.spec0.17(i32 0) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL7]], label [[LAND_END]], label [[LAND_LHS_TRUE8:%.*]]
; CHECK:       land.lhs.true8:
; CHECK-NEXT:    [[CALL9:%.*]] = call zeroext i1 @odd.spec0.15(i32 1) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL9]], label [[LAND_LHS_TRUE10:%.*]], label [[LAND_END]]
; CHECK:       land.lhs.true10:
; CHECK-NEXT:    [[CALL11:%.*]] = call zeroext i1 @odd.spec0.13(i32 2) #[[ATTR1]]
; CHECK-NEXT:    br i1 [[CALL11]], label [[LAND_END]], label [[LAND_RHS:%.*]]
; CHECK:       land.rhs:
; CHECK-NEXT:    [[CALL12:%.*]] = call zeroext i1 @odd.spec0(i32 3) #[[ATTR1]]
; CHECK-NEXT:    br label [[LAND_END]]
; CHECK:       land.end:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, [[LAND_LHS_TRUE10]] ], [ false, [[LAND_LHS_TRUE8]] ], [ false, [[LAND_LHS_TRUE6]] ], [ false, [[LAND_LHS_TRUE4]] ], [ false, [[LAND_LHS_TRUE2]] ], [ false, [[LAND_LHS_TRUE]] ], [ false, [[ENTRY:%.*]] ], [ [[CALL12]], [[LAND_RHS]] ]
; CHECK-NEXT:    ret i1 [[TMP0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@loop.spec0
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @loop(i32 5) #[[ATTR1]]
; CHECK-NEXT:    [[CALL1:%.*]] = call i32 @loop(i32 5) #[[ATTR1]]
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[CALL]], [[CALL1]]
; CHECK-NEXT:    ret i32 [[ADD]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial.spec0
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 4, 2
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 4, 1
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 4, [[CALL]]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ [[MUL]], [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial.spec0.4
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 3, 2
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 3, 1
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 3, [[CALL]]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ [[MUL]], [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial.spec0.6
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 2, 2
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 2, 1
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 2, [[CALL]]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ [[MUL]], [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial.spec0.8
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 1, 2
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 1, 1
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 1, [[CALL]]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ [[MUL]], [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@factorial.spec0.10
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 0, 2
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 0, 1
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @factorial(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 0, [[CALL]]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ [[MUL]], [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
;
; CHECK-LABEL: define {{[^@]+}}@odd.spec0
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 3, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 3, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @even(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 0, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@odd.spec0.13
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 2, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 2, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @even(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 0, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@odd.spec0.15
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 1, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 1, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @even(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 0, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@odd.spec0.17
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 0, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 0, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @even(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 0, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@even.spec0
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 3, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 3, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @odd(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 1, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@even.spec0.20
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 2, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 2, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @odd(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 1, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@even.spec0.22
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 1, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 1, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @odd(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 1, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
;
; CHECK-LABEL: define {{[^@]+}}@even.spec0.24
; CHECK-SAME: (i32 [[X:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 0, 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    br label [[COND_END:%.*]]
; CHECK:       cond.false:
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 0, 1
; CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @odd(i32 [[SUB]]) #[[ATTR1]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CALL]] to i32
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND:%.*]] = phi i32 [ 1, [[COND_TRUE]] ], [ [[CONV]], [[COND_FALSE]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[COND]], 0
; CHECK-NEXT:    ret i1 [[TOBOOL]]
;
