#!/bin/bash

set -x
set -e
set -o pipefail

SOURCE=$HOME/llvm-project

BLD=~/llvm-build/llvm/bin

TESTDIR=$SOURCE/llvm/test/Transforms/FunctionSpecialization

TMPDIR=/tmp/hacking

rm -rf ~/llvm-build/rawprof

mkdir -p $TMPDIR
rm -f $TMPDIR/input.ll $TMPDIR/output.ll


cd ~/llvm-build/llvm
ninja clang llc opt

cd $TMPDIR

echo "Calling clang O0"
$BLD/clang -O0 -Xclang -disable-O0-optnone -ffreestanding ~/llvm-project/clang/test/Sema/attr-alwaysspecialize.cpp -emit-llvm -S -o $TMPDIR/input.tmp.ll

echo "Calling clang O1"
$BLD/clang -O1 -ffreestanding ~/llvm-project/clang/test/Sema/attr-alwaysspecialize.cpp -emit-llvm -S -o /dev/null


echo "Calling opt instcombine"
$BLD/opt $TMPDIR/input.tmp.ll -passes='module(instcombine)' -S -o $TMPDIR/input.ll

echo "Calling opt on passes"
# globaldce would remove unused statics
# deadargelim is useful for removing the arguments


$BLD/opt $TMPDIR/input.ll -passes='module(always-specialize)' -S -o $TMPDIR/output.ll

# $BLD/opt $TMPDIR/input.ll -passes='module(always-specialize,always-inline,deadargelim,instcombine,simplifycfg)' -S -o $TMPDIR/output.ll


for c in $TESTDIR/*.c ; do
    ll=$(echo $c | sed 's_\(.*\).c_\1.ll_g')
    echo "Compiling $c -> $ll"
    rm -f $ll
    # check-globals doesn't cover new functions
    # --include-generated-funcs might do, isn't documented
    echo '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature --include-generated-funcs' >> $ll
    echo "; RUN: opt -S --passes=always-specialize < %s | FileCheck %s" >> $ll
    $BLD/clang -O0 -Xclang -disable-O0-optnone -mllvm -enable-always-specialize=false -ffreestanding $c -emit-llvm -S -o $ll.c.tmp
    $BLD/opt --passes=mem2reg $ll.c.tmp -S -o $ll.opt.tmp
    cat $ll.opt.tmp | egrep -v '; ModuleID|source_filename' >> $ll
    sed -i 's_noundef __g' $ll
    rm $ll.*.tmp
    llvm_regen.sh $(echo $ll | sed 's_.*llvm-project/llvm/test/__g')
    # Run that single test case
    $BLD/llvm-lit -v $ll
done

exit 0

BUILD=~/llvm-build/llvm
STAGING=$BUILD/../docs
OUTPUT=/mnt/scratch/docs

mkdir -p $STAGING $OUTPUT

# Hoping the cmake flags:
#      -DLLVM_BUILD_INSTRUMENTED_COVERAGE=On \
#      -DLLVM_PROFILE_DATA_DIR=$BDIR/rawprof \
# are sufficient to build and opt which writes profile info to $BDIR/rawprof
# i.e. ~/llvm-build/rawprof
# Did not work at all with the local clang build, trying the debian clang-16 package

# might be able to use ninja generate-coverage-report instead of this which would be much better
# except it runs all the llvm tests and they run very slowly

# assuming built with debian's clang-16 since the local build of compiler-rt is falling over
python3 $SOURCE/llvm/utils/prepare-code-coverage-artifact.py \
        --preserve-profiles \
        --unified-report \
        -C $BUILD \
        /usr/bin/llvm-profdata-16 \
        /usr/bin/llvm-cov-16 \
        ~/llvm-build/rawprof/ \
        $STAGING \
        $BUILD/bin/clang $BUILD/bin/opt $BUILD/bin/llc 

rsync -ahP $STAGING/ $OUTPUT/

